---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: shell
  script: centos2ol.sh

platforms:
  # This name is a bit odd as it will be added and
  # removed from the Chef Server multiple times during testing
  # It can be searched via keyword: chef-deploy

  - name: centos-6.10
    driver_config:
      box: bento/centos-6.10

  - name: centos-7.9
    driver_config:
      box: bento/centos-7.9

  - name: centos-8.3
    driver_config:
      box: bento/centos-8.3

suites:
  - name: default
    provisioner:
      arguments: ['-k']
    run_list:
    attributes:
    verifier:
      inspec_tests:
        - test/integration/default
  - name: uek
    run_list:
    attributes:
    verifier:
      inspec_tests:
        - test/integration/uek
